### ISSUE TITLE
Can't install via pip on windows

### ISSUE THREAD

**Issue by JMans15** [olokelo/jxlpy#10]
Hi, I tried to install jxlpy on windows using ```pip install jxlpy``` and got this error: ```ValueError: '_jxlpy/_jxl.pyx' doesn't match any files```

**Comment by C0rn3j** [comment]
This is not a Windows exclusive issue, the Github 0.9.1 release is correct, the 0.9.1 release on PyPi is broken.

So is 0.9.2, but that does not have a Github release to compare to.

```
python setup.py build
python setup.py install --root="$pkgdir"
```

```
Traceback (most recent call last):
  File "/home/c0rn3j/AUR/python-jxlpy/src/jxlpy-0.9.2/setup.py", line 37, in <module>
    ext_modules=cythonize([jxlpy_ext]),
  File "/home/c0rn3j/.local/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 970, in cythonize
    module_list, module_metadata = create_extension_list(
  File "/home/c0rn3j/.local/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
    for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
  File "/home/c0rn3j/.local/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
    raise ValueError(error_msg)
ValueError: '_jxlpy/_jxl.pyx' doesn't match any files
```

**Comment by inversepixel** [comment]
I have the same problem on Windows. Any estimation on when this will be fixed or any workarounds?
Many thanks!
/Tomas

**Comment by alexjc** [comment]
It shows the same problem on MacOS as it's building from source.  I the binaries work, but not the source ones?

**Comment by zhou13** [comment]
It seems that
```
pip install git+https://github.com/olokelo/jxlpy
```
works for me

**Comment by C0rn3j** [comment]
The freshly released 0.9.3 github version is now correctly packaged.

PyPi seems to ship the _jxl.cpp still instead of _jxl.pyx, but `pip install jxlpy` now runs fine in a Linux venv on 3.11.6.

So I suppose this can be closed if Windows users can also confirm.

**Comment by c4yg70** [comment]
> The freshly released 0.9.3 github version is now correctly packaged.
> 
> PyPi seems to ship the _jxl.cpp still instead of _jxl.pyx, but `pip install jxlpy` now runs fine in a Linux venv on 3.11.6.
> 
> So I suppose this can be closed if Windows users can also confirm.

Tested and works great in all below settings:
- install ver0.9.3 from pypi
- windows 11 23H2 22631.3155
- Processor
  1. Intel ultra5 125H, 12700H,  i7-7700k, 
  2. AMD 7840H, 7950X, 7950X3D
- Python 3.11, 3.12
- Docker Python 3.11, 3.12  alpine, debian

Could not work even build loaclly:
- LoongArch Processor
- python 3.8
- rk3568(arm64) python3.11

**Comment by olokelo** [comment]
Hi, thanks for testing on all those platforms.

If you have time you could also try building from master branch source modifying `setup.py` like [here](https://github.com/olokelo/jxlpy/issues/6#issuecomment-1934370187). For some reason `.pyx` file wasn't included in latest sdist on PyPI but maybe that 'hack' will make future releases build without issues.

Also I'm glad you had success building it on Windows.

**Comment by c4yg70** [comment]
I use PDM for my package manager so maybe thanks to pdm solved that problem for me?
I tried again yesterday and here is the result: directly calling pypi from python-windows installing ver0.9.3 would refuse to work, but calling from docker or using pdm worked fine. However, I do have libjxl compiled externally on my system, so others may fail to install. I would like to try building from source lately this week.

Also, libjxl has updated and wish to see a minor version update for jxlpy.

Best wishes.

**Comment by olokelo** [comment]
jxlpy 0.9.4 now ships with libjxl 0.10.1 and possibly fixed source distribution. You can try it :)

**Comment by moltenform** [comment]
How I got jxlpy to install and work on Windows:

I have Visual Studio 2022 Community (free) installed, and so if the below steps don't work you should either 1) install the "windows sdk" or 2) install Visual Studio 2022 Community. This way, there is a C++ compiler available.

```
Confirmed to work on x64 Windows 11:

1) 
Go to 
https://github.com/libjxl/libjxl/releases
and download the v0.11.1 release of 
"jxl-x64-windows-static.zip".

2)
Go to the location of the python.exe you want to install for.
Make a directory PCbuild/amd64
Extract the contents of jxl-x64-windows-static.zip into that directory.
For example,
If your python is C:\path\to\python.exe
There should now exist C:\path\to\PCbuild\amd64\jxl.lib

3)
Go to 
https://github.com/libjxl/libjxl/releases
and download the v0.11.1 source code of 
"libjxl-0.11.1.zip".

4) 
Unzip libjxl-0.11.1.zip and go to lib/include/jxl
Copy all of these .h files into Python's include directory,
For example,
If your python is C:\path\to\python.exe
There should now exist C:\path\to\include\jxl\types.h

5)
Copy in the 3 generated headers. I got these contents by looking online,
or you can just paste in these values:

====== the file jxl_export.h has the content ========
#ifndef JXL_EXPORT_H
#define JXL_EXPORT_H

#define JXL_EXPORT

// MSVC requires [[deprecated]]
#define JXL_DEPRECATED [[deprecated]]

#endif /* JXL_EXPORT_H */

====== the file jxl_threads_export.h has the content ========
#ifndef JXL_THREADS_EXPORT_H
#define JXL_THREADS_EXPORT_H

#define JXL_THREADS_EXPORT

#endif /* JXL_THREADS_EXPORT_H */

====== the file version.h has the content ========
/* Copyright (c) the JPEG XL Project Authors. All rights reserved.
 *
 * Use of this source code is governed by a BSD-style
 * license that can be found in the LICENSE file.
 */

/** @addtogroup libjxl_common
 * @{
 * @file version.h
 * @brief libjxl version information
 */

#ifndef JXL_VERSION_H_
#define JXL_VERSION_H_

#define JPEGXL_MAJOR_VERSION 0 ///< JPEG XL Major version
#define JPEGXL_MINOR_VERSION 11 ///< JPEG XL Minor version
#define JPEGXL_PATCH_VERSION 1 ///< JPEG XL Patch version

#define JPEGXL_COMPUTE_NUMERIC_VERSION(major,minor,patch) ((major<<24) | (minor<<16) | (patch<<8) | 0)

/* Numeric representation of the version */
#define JPEGXL_NUMERIC_VERSION JPEGXL_COMPUTE_NUMERIC_VERSION(JPEGXL_MAJOR_VERSION,JPEGXL_MINOR_VERSION,JPEGXL_PATCH_VERSION)

#endif /* JXL_VERSION_H_ */

/** @}*/


6) 
Go to 
https://github.com/olokelo/jxlpy/releases/tag/0.9.5
and download the source code for release 0.9.5

7)
Unzip 
jxlpy-0.9.5.zip 
to a folder named jxlpy-0.9.5
and edit setup.py

Look for the line that says jxlpy_ext = Extension(
Before that line add the code
import os
pythonPath = os.path.abspath(sys.executable)
dirLibs = os.path.dirname(pythonPath) + '\\PCbuild\\amd64'


Change the line with extra_compile_args so that it says
extra_compile_args=['-O2', '/MT'],


Change the line with extra_link_args so that it says
extra_link_args=[
        dirLibs + "\\brotlidec.lib",
        dirLibs + "\\brotlienc.lib",
        dirLibs + "\\hwy.lib",
        dirLibs + "\\jxl.lib",
        dirLibs + "\\jxl_cms.lib",
        dirLibs + "\\jxl_extras_codec.lib",
        dirLibs + "\\jxl_jni.lib",
        dirLibs + "\\jxl_threads.lib",
]

8)
Open a cmd prompt
cd to the directory with jxlpy-0.9.5
The file setup.py should be in the same directory.

9)
Run the command
py -m pip install .
or 
python -m pip install .

The installation hopefully wil succeed! Then you can run the examples like

====== the file example.py has the content ========
import jxlpy

with open(r"C:\path\to\test.jxl", 'rb') as f:
    fc = f.read()

dec = jxlpy.JXLPyDecoder(fc)
info = dec.get_info()
print('Information about image:', info)

```

**Comment by miaLDN** [comment]
Is there any progress on this?

**Comment by moltenform** [comment]
@olokelo If I made a PR to help with this, could it get merged?

**Comment by miaLDN** [comment]
Seeing as OP has stated they are not into Windows development, and have Windows support as very low - I think alternatives are needed.

@moltenform would you be able fork and release of pypi?

@olokelo you should make clear on PyPi that this does not work on Windows please; and it should detect Windows and gracefully error, rather than random cryptic messages people are getting attempting to `pip install` this package.

**Comment by moltenform** [comment]
Am busy with other projects at the moment, it does seem like this project isn't actively maintained though, so a fork might be a good idea.

**Comment by mahmoudimus** [comment]
I've made a build script that *should* technically build it for you. 

Create a virtual env:

```powershell
python -m venv .venv
.\.venv\Scripts\Activate.ps1

# sanity check
where python
python -c "import sys; print(sys.executable)"

# run installer
.\Install-Jxlpy.ps1
```

Use the script here: https://gist.github.com/mahmoudimus/210e7faa2c0bcda8e95fe9528149c638 

or below for convenience:

```powershell
<#
.SYNOPSIS
  Automates the JPEG XL + jxlpy build/install steps on Windows for a specific Python.

.EXAMPLE
  .\Install-Jxlpy.ps1 -PythonExe "C:\path\to\python.exe" -WorkDir "C:\temp\jxlpy-build"

.NOTES
  - Downloads:
      libjxl v0.11.1 Windows static zip
      libjxl v0.11.1 source zip (headers)
      jxlpy v0.9.5 source zip
  - Installs libs to:   <PythonDir>\PCbuild\amd64
  - Installs headers to:<PythonDir>\include\jxl
  - Patches jxlpy setup.py and runs: <PythonExe> -m pip install .
  - Sanity Checks:
      Test-Path "C:\path\to\PCbuild\amd64\jxl.lib"
      Test-Path "C:\path\to\include\jxl\types.h"
      Test-Path "C:\path\to\include\jxl\version.h"  
#>

[CmdletBinding()]
param(
  [Parameter(Mandatory = $false)]
  [string]$PythonExe,

  [Parameter(Mandatory = $false)]
  [string]$WorkDir = (Join-Path $PWD "jxlpy-build"),

  [Parameter(Mandatory = $false)]
  [switch]$SkipPipInstall
)

if (-not $PythonExe) {
  $PythonExe = (Get-Command python.exe).Source
}

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-Info($msg) { Write-Host "[INFO]  $msg" -ForegroundColor Cyan }
function Write-Warn($msg) { Write-Host "[WARN]  $msg" -ForegroundColor Yellow }
function Write-Err($msg) { Write-Host "[ERROR] $msg" -ForegroundColor Red }

function Assert-FileExists([string]$Path, [string]$Label) {
  if (-not (Test-Path -LiteralPath $Path)) {
    throw "$Label not found: $Path"
  }
}

function Ensure-Dir([string]$Path) {
  if (-not (Test-Path -LiteralPath $Path)) {
    New-Item -ItemType Directory -Path $Path | Out-Null
  }
}

function Assert-FileSha256([string]$Path, [string]$ExpectedSha256) {
  if (-not $ExpectedSha256) { return }  # allow "no hash provided"
  $actual = (Get-FileHash -Algorithm SHA256 -LiteralPath $Path).Hash.ToLowerInvariant()
  $expected = $ExpectedSha256.ToLowerInvariant().Replace(" ", "")
  if ($actual -ne $expected) {
    throw "SHA256 mismatch for $Path`nExpected: $expected`nActual:   $actual"
  }
}

function Download-File([string]$Url, [string]$OutFile, [string]$ExpectedSha256) {
  Ensure-Dir (Split-Path -Parent $OutFile)

  if (Test-Path -LiteralPath $OutFile) {
    $size = (Get-Item -LiteralPath $OutFile).Length
    if ($size -gt 0) {
      try {
        Assert-FileSha256 $OutFile $ExpectedSha256
        Write-Info "Using cached (SHA OK): $OutFile"
        return
      }
      catch {
        Write-Warn "Cached file failed SHA check; re-downloading: $OutFile"
        Remove-Item -LiteralPath $OutFile -Force -ErrorAction SilentlyContinue
      }
    }
    else {
      Write-Warn "Cached file exists but is empty; re-downloading: $OutFile"
      Remove-Item -LiteralPath $OutFile -Force -ErrorAction SilentlyContinue
    }
  }

  Write-Info "Downloading: $Url"
  try {
    [Net.ServicePointManager]::SecurityProtocol =
    [Net.ServicePointManager]::SecurityProtocol -bor
    [Net.SecurityProtocolType]::Tls12
  }
  catch {}

  Invoke-WebRequest -Uri $Url -OutFile $OutFile -UseBasicParsing
  Assert-FileExists $OutFile "Download output"
  # Verify after download
  Assert-FileSha256 $OutFile $ExpectedSha256
  Write-Info "Verified (SHA OK): $OutFile"  
}

function Expand-Zip([string]$ZipPath, [string]$DestDir) {
  Write-Info "Extracting: $ZipPath -> $DestDir"

  if (Test-Path -LiteralPath $DestDir) {
    Remove-Item -LiteralPath $DestDir -Recurse -Force -ErrorAction SilentlyContinue
  }
  New-Item -ItemType Directory -Path $DestDir -Force | Out-Null

  Expand-Archive -LiteralPath $ZipPath -DestinationPath $DestDir -Force
}

function Get-PythonPrefix([string]$PythonExePath) {
  $PythonPrefix = & $PythonExe -c "import sys; print(sys.prefix)"
  return $PythonPrefix.Trim()
}

function Backup-File([string]$Path) {
  $bak = "$Path.bak"
  Copy-Item -LiteralPath $Path -Destination $bak -Force
  Write-Info "Backed up: $Path -> $bak"
}

function Set-TextFile([string]$Path, [string]$Content) {
  # Use ASCII to keep headers simple & predictable
  Set-Content -LiteralPath $Path -Value $Content -Encoding Ascii
}

function Patch-SetupPy([string]$SetupPyPath) {
  Write-Info "Patching setup.py: $SetupPyPath"
  Backup-File $SetupPyPath

  $text = Get-Content -LiteralPath $SetupPyPath -Raw

  # 1) Insert pythonPath/dirLibs block right before "jxlpy_ext = Extension("
  $needle = "jxlpy_ext = Extension("
  if ($text -notmatch [regex]::Escape($needle)) {
    throw "Could not find '$needle' in setup.py; patching aborted."
  }

  $insertBlock = @"
import os
import sys

pythonPath = os.path.abspath(sys.executable)
venvRoot = os.path.dirname(os.path.dirname(pythonPath)) if os.path.basename(os.path.dirname(pythonPath)).lower() == "scripts" else os.path.dirname(pythonPath)
dirLibs = venvRoot + r'\\PCbuild\\amd64'

"@

  # Only insert if not already present
  if ($text -notmatch "dirLibs\s*=\s*venvRoot\s*\+\s*'\\\\PCbuild\\\\amd64'") {
    $text = $text -replace [regex]::Escape($needle), ($insertBlock + $needle)
  }
  else {
    Write-Warn "setup.py already seems to contain dirLibs block; skipping insertion."
  }

  # 2) Replace extra_compile_args to exactly: extra_compile_args=['-O2', '/MT'],
  # Try to match "extra_compile_args=..." on one line
  $text = [regex]::Replace(
    $text,
    "extra_compile_args\s*=\s*\[[^\]]*\]\s*,",
    "extra_compile_args=['-O2', '/MT'],"
  )

  # 3) Replace extra_link_args block with the requested list.
  $newLinkArgs = @"
extra_link_args=[
        dirLibs + r"\brotlicommon.lib",
        dirLibs + r"\brotlidec.lib",
        dirLibs + r"\brotlienc.lib",
        dirLibs + r"\hwy.lib",
        dirLibs + r"\jxl.lib",
        dirLibs + r"\jxl_cms.lib",
        dirLibs + r"\jxl_extras_codec.lib",
        dirLibs + r"\jxl_jni.lib",
        dirLibs + r"\jxl_threads.lib",
],
"@

  $patternLinkArgs = "extra_link_args\s*=\s*\[[\s\S]*?\]\s*,"
  if ($text -match $patternLinkArgs) {
    $text = [regex]::Replace($text, $patternLinkArgs, $newLinkArgs)
  }
  else {
    Write-Warn "Could not find an existing extra_link_args=[...] block to replace. Trying to inject into Extension(...) call."

    # As a fallback, add after extra_compile_args if present? Probably not needed.
    if ($text -match "extra_compile_args=\['-O2', '/MT'\],") {
      $text = $text -replace "extra_compile_args=\['-O2', '/MT'\],", ("extra_compile_args=['-O2', '/MT']," + "`r`n    " + $newLinkArgs)
    }
    else {
      throw "Fallback injection failed; please patch extra_link_args manually."
    }
  }

  Set-Content -LiteralPath $SetupPyPath -Value $text -Encoding UTF8
}

Assert-FileExists $PythonExe "PythonExe"
$PythonDir = Get-PythonPrefix $PythonExe

Write-Info "Target python.exe: $PythonExe"
Write-Info "Python directory:  $PythonDir"
Write-Info "Work directory:    $WorkDir"
Ensure-Dir $WorkDir

# URLs
$libjxlWinUrl = "https://github.com/libjxl/libjxl/releases/download/v0.11.1/jxl-x64-windows-static.zip"
$libjxlSrcUrl = "https://github.com/libjxl/libjxl/archive/refs/tags/v0.11.1.zip"
$jxlpyUrl = "https://github.com/olokelo/jxlpy/archive/refs/tags/0.9.5.zip"

$downloads = Join-Path $WorkDir "downloads"
Ensure-Dir $downloads

$libjxlWinZip = Join-Path $downloads "jxl-x64-windows-static.zip"
$libjxlSrcZip = Join-Path $downloads "libjxl-0.11.1.zip"
$jxlpyZip = Join-Path $downloads "jxlpy-0.9.5.zip"

Download-File $libjxlWinUrl $libjxlWinZip "8F53EBCE91820C30C9FC9294F06380213C1E2E66B361718880580246B2BE008E"
Download-File $libjxlSrcUrl $libjxlSrcZip "240F5D6CB725B067C7F153B3B9C3DC9621C9C96D4229DC278E2C5678944E24A2" 
Download-File $jxlpyUrl     $jxlpyZip     "DC028B25484651397C5E34D4417DD96F1BE22F9115015B9C21725DAB13205604"

# Step 2: Extract windows static libs into <PythonDir>\PCbuild\amd64
$pcbuildAmd64 = Join-Path $PythonDir "PCbuild\amd64"
Ensure-Dir $pcbuildAmd64

# Extract to temp
$tmpLibExtract = Join-Path $WorkDir "extract-libjxl-win"
Expand-Zip $libjxlWinZip $tmpLibExtract

# Find where jxl.lib actually landed (zip may have nested folders)
Write-Info "Searching extracted files for jxl.lib..."
$foundJxlLib = Get-ChildItem -LiteralPath $tmpLibExtract -Recurse -File -Filter "jxl.lib" -ErrorAction SilentlyContinue | Select-Object -First 1
if (-not $foundJxlLib) {
  Write-Warn "Could not find jxl.lib under $tmpLibExtract. Top-level contents:"
  Get-ChildItem -LiteralPath $tmpLibExtract -Force | ForEach-Object { Write-Host "  - $($_.FullName)" }
  throw "jxl.lib not found in extracted windows static zip. The zip layout may have changed."
}

$libRoot = Split-Path -Parent $foundJxlLib.FullName
Write-Info "Found jxl.lib at: $($foundJxlLib.FullName)"
Write-Info "Copying lib bundle from: $libRoot -> $pcbuildAmd64"

Get-ChildItem -LiteralPath $libRoot -Force | Copy-Item -Destination $pcbuildAmd64 -Recurse -Force

$expectedLib = Join-Path $pcbuildAmd64 "jxl.lib"
if (-not (Test-Path -LiteralPath $expectedLib)) {
  Write-Warn "Did not find expected $expectedLib. Listing files in ${pcbuildAmd64}:"
  Get-ChildItem -LiteralPath $pcbuildAmd64 | ForEach-Object { Write-Host "  - $($_.Name)" }
  throw "jxl.lib not found after extraction/copy. The zip layout may have changed."
}
Write-Info "Found: $expectedLib"

# Step 4: Copy libjxl headers into <PythonDir>\include\jxl
$tmpSrcExtract = Join-Path $WorkDir "extract-libjxl-src"
Expand-Zip $libjxlSrcZip $tmpSrcExtract

# The zip typically creates libjxl-0.11.1\...
$srcRoot = Join-Path $tmpSrcExtract "libjxl-0.11.1"
if (-not (Test-Path -LiteralPath $srcRoot)) {
  # Try: detect single top directory
  $top = Get-ChildItem -LiteralPath $tmpSrcExtract -Directory | Select-Object -First 1
  if ($null -ne $top) { $srcRoot = $top.FullName }
}
Assert-FileExists $srcRoot "libjxl source root"

# Find the jxl header folder anywhere under the extracted source
Write-Info "Searching extracted source for header folder: lib\include\jxl"
$srcHeadersDir = Get-ChildItem -LiteralPath $tmpSrcExtract -Recurse -Directory -ErrorAction SilentlyContinue |
Where-Object { $_.FullName -match "\\lib\\include\\jxl$" } |
Select-Object -First 1

if (-not $srcHeadersDir) {
  throw "Could not find lib\\include\\jxl in extracted libjxl source zip."
}

$srcHeaders = $srcHeadersDir.FullName
Write-Info "Using headers directory: $srcHeaders"
Assert-FileExists $srcHeaders "libjxl headers folder"

$pyIncludeJxl = Join-Path $PythonDir "Include\jxl"
Ensure-Dir $pyIncludeJxl

Write-Info "Copying *.h headers: $srcHeaders -> $pyIncludeJxl"
Get-ChildItem -LiteralPath $srcHeaders -Force | Copy-Item -Destination $pyIncludeJxl -Recurse -Force

# Step 5: Create 3 generated headers in Python include\jxl
Write-Info "Writing generated headers into: $pyIncludeJxl"

$jxl_export_h = @'
#ifndef JXL_EXPORT_H
#define JXL_EXPORT_H

#define JXL_EXPORT

// MSVC requires [[deprecated]]
#define JXL_DEPRECATED [[deprecated]]

#endif /* JXL_EXPORT_H */
'@

$jxl_threads_export_h = @'
#ifndef JXL_THREADS_EXPORT_H
#define JXL_THREADS_EXPORT_H

#define JXL_THREADS_EXPORT

#endif /* JXL_THREADS_EXPORT_H */
'@

$version_h = @'
/* Copyright (c) the JPEG XL Project Authors. All rights reserved.
 *
 * Use of this source code is governed by a BSD-style
 * license that can be found in the LICENSE file.
 */

/** @addtogroup libjxl_common
 * @{
 * @file version.h
 * @brief libjxl version information
 */

#ifndef JXL_VERSION_H_
#define JXL_VERSION_H_

#define JPEGXL_MAJOR_VERSION 0 ///< JPEG XL Major version
#define JPEGXL_MINOR_VERSION 11 ///< JPEG XL Minor version
#define JPEGXL_PATCH_VERSION 1 ///< JPEG XL Patch version

#define JPEGXL_COMPUTE_NUMERIC_VERSION(major,minor,patch) ((major<<24) | (minor<<16) | (patch<<8) | 0)

/* Numeric representation of the version */
#define JPEGXL_NUMERIC_VERSION JPEGXL_COMPUTE_NUMERIC_VERSION(JPEGXL_MAJOR_VERSION,JPEGXL_MINOR_VERSION,JPEGXL_PATCH_VERSION)

#endif /* JXL_VERSION_H_ */

/** @}*/
'@

Set-TextFile (Join-Path $pyIncludeJxl "jxl_export.h")          $jxl_export_h
Set-TextFile (Join-Path $pyIncludeJxl "jxl_threads_export.h")  $jxl_threads_export_h
Set-TextFile (Join-Path $pyIncludeJxl "version.h")             $version_h

# Step 6-7: Download + unzip jxlpy 0.9.5 and patch setup.py
$tmpJxlpyExtract = Join-Path $WorkDir "extract-jxlpy"
Expand-Zip $jxlpyZip $tmpJxlpyExtract

# GitHub tag zip usually expands into jxlpy-0.9.5\...
$jxlpyRoot = Join-Path $tmpJxlpyExtract "jxlpy-0.9.5"
if (-not (Test-Path -LiteralPath $jxlpyRoot)) {
  $top = Get-ChildItem -LiteralPath $tmpJxlpyExtract -Directory | Select-Object -First 1
  if ($null -ne $top) { $jxlpyRoot = $top.FullName }
}
Assert-FileExists $jxlpyRoot "jxlpy root folder"

$setupPy = Join-Path $jxlpyRoot "setup.py"
Assert-FileExists $setupPy "jxlpy setup.py"

Patch-SetupPy $setupPy

Write-Info "Patched setup.py successfully."

# Step 9: pip install .
if (-not $SkipPipInstall) {
  Write-Info "Installing with pip using: $PythonExe"
  Push-Location $jxlpyRoot
  try {
    & $PythonExe -m pip install --upgrade pip setuptools wheel
    & $PythonExe -m pip install . --no-build-isolation
  }
  finally {
    Pop-Location
  }
  Write-Info "Done. If build succeeded, you can now import jxlpy."
}
else {
  Write-Warn "SkipPipInstall set; not running pip install. Patched sources are at: $jxlpyRoot"
}

Write-Info "All steps completed."
```

**Comment by cidrei** [comment]
I just uploaded some pre-built wheels of 0.9.5 for all the currently supported pythons (i. e. 3.10-3.14), along with the step-by-step instructions I used to build them [over here](https://github.com/cidrei/jxlpy-win_x64/releases/tag/0.9.5). I have no intention of uploading them to PyPI, but they're up for people that want them.
