### ISSUE TITLE
Pillow ValueError

### ISSUE THREAD

**Issue by BigBoyBarney** [olokelo/jxlpy#22]
Hi! 
First of all, thank you for this project! I was trying to get this to work with Pillow using the encode-decode example.
```python
from PIL import Image
from jxlpy import JXLImagePlugin

im = Image.open('1.jxl')
im = im.resize((im.width*2, im.height*2))
im.save('test_2x.jxl', lossless=True, effort=7)
```

but I get the following error:
```
/usr/bin/python3.12 /home/barney/Documents/Programming/Random/Pillow jxl.py 
Traceback (most recent call last):
  File "/home/barney/Documents/Programming/Random/Pillow jxl.py", line 5, in <module>
    im = im.resize((im.width*2, im.height*2))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/barney/.local/lib/python3.12/site-packages/PIL/Image.py", line 2164, in resize
    self.load()
  File "/home/barney/.local/lib/python3.12/site-packages/jxlpy/JXLImagePlugin.py", line 63, in load
    return super().load()
           ^^^^^^^^^^^^^^
  File "/home/barney/.local/lib/python3.12/site-packages/PIL/ImageFile.py", line 227, in load
    self.im = Image.core.map_buffer(
              ^^^^^^^^^^^^^^^^^^^^^^
ValueError: buffer is not large enough
```

then I  tried

```python
from PIL import Image
from jxlpy import JXLImagePlugin

with open("1.jxl", "rb") as f:
    with Image.open(f) as im:
        im.show()
```
which results in 
```
/usr/bin/python3.12 /home/barney/Documents/Programming/Random/Pillow jxl.py 
Traceback (most recent call last):
  File "/home/barney/Documents/Programming/Random/Pillow jxl.py", line 6, in <module>
    im.show()
  File "/home/barney/.local/lib/python3.12/site-packages/PIL/Image.py", line 2494, in show
    _show(self, title=title)
  File "/home/barney/.local/lib/python3.12/site-packages/PIL/Image.py", line 3539, in _show
    ImageShow.show(image, **options)
  File "/home/barney/.local/lib/python3.12/site-packages/PIL/ImageShow.py", line 62, in show
    if viewer.show(image, title=title, **options):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/barney/.local/lib/python3.12/site-packages/PIL/ImageShow.py", line 86, in show
    return self.show_image(image, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/barney/.local/lib/python3.12/site-packages/PIL/ImageShow.py", line 113, in show_image
    return self.show_file(self.save_image(image), **options)
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/barney/.local/lib/python3.12/site-packages/PIL/ImageShow.py", line 109, in save_image
    return image._dump(format=self.get_format(image), **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/barney/.local/lib/python3.12/site-packages/PIL/Image.py", line 604, in _dump
    self.save(filename, format, **options)
  File "/home/barney/.local/lib/python3.12/site-packages/PIL/Image.py", line 2439, in save
    save_handler(self, fp, filename)
  File "/home/barney/.local/lib/python3.12/site-packages/PIL/PngImagePlugin.py", line 1224, in _save_all
    _save(im, fp, filename, save_all=True)
  File "/home/barney/.local/lib/python3.12/site-packages/PIL/PngImagePlugin.py", line 1237, in _save
    for im_frame in ImageSequence.Iterator(im_seq):
  File "/home/barney/.local/lib/python3.12/site-packages/PIL/ImageSequence.py", line 56, in __next__
    self.im.seek(self.position)
  File "/home/barney/.local/lib/python3.12/site-packages/jxlpy/JXLImagePlugin.py", line 41, in seek
    raise NotImplementedError(
NotImplementedError: Seeking more than one frame forward is currently not supported.
```

Any help would be appreciated!
Thanks!

**Comment by olokelo** [comment]
Hello,
Thank you for reporting this issue. The first part about the buffer error seems to be more related to Pillow itself. [see here](https://github.com/python-pillow/Pillow/pull/6510/files)
Could you please try doing the same with non-jxl image to verify that?

I was able to replicate your second issue. It seems to be a bug in `jxlpy` Pillow integration. 
[This line](https://github.com/olokelo/jxlpy/blob/263f07385c38a86b8d4745a1e9c56909d46958b5/jxlpy/JXLImagePlugin.py#L39) in `JXLImagePlugin` obviously should also take into consideration user seeking to the same frame. I changed that but from what I can tell, Pillow for some reason tries to seek to next frame which doesn't exist when calling `im.show()`. This confuses `jxlpy` as it doesn't know how many frames does a jxl image have until its fully decoded. I've also ran into issues where Pillow is getting stuck in a loop seeking frame by frame up to infinity.
When calling `im.save()` everything seems fine and Pillow doesn't issue unnecessary seeks. 

I will probably take a look at it tomorrow.

**Comment by BigBoyBarney** [comment]
Thank you for taking a look!
```python
from PIL import Image
from jxlpy import JXLImagePlugin

im = Image.open('1.png')
im = im.resize((im.width*2, im.height*2))
im.save('test_2x.jxl', lossless=True, effort=7)
```
the above works as intended^ :D

**Comment by olokelo** [comment]
Hi!
Please try the most recent version of jxlpy. I think I figured out the issue.

**Comment by BigBoyBarney** [comment]
Hi! Thanks for looking into it
I tried it with version 0.9.4, and Pillow no longer recognises jxl images.
for both
```python
from PIL import Image
from jxlpy import JXLImagePlugin

with open("1.jxl", "rb") as f:
    with Image.open(f) as im:
        im.show()
```
and
```python
from PIL import Image
from jxlpy import JXLImagePlugin

im = Image.open('1.jxl')
im = im.resize((im.width*2, im.height*2))
im.save('test_2x.jxl', lossless=True, effort=7)
```
I get the following error:
```
/usr/bin/python3.12 /home/barney/Documents/Programming/Random/Pillow jxl.py 
Traceback (most recent call last):
  File "/home/barney/Documents/Programming/Random/Pillow jxl.py", line 5, in <module>
    with Image.open(f) as im:
         ^^^^^^^^^^^^^
  File "/home/barney/.local/lib/python3.12/site-packages/PIL/Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='1.jxl'>
```

**Comment by olokelo** [comment]
Hi,
I honestly have no idea what might be going on now. I've tested jxlpy from PyPI on Python 3.12 and it seems to work fine with Pillow.
Could you tell me what OS are you using?
Maybe also what's your input image?
Could you please test once again on different set of images for example from [jpegxl.info](https://jpegxl.info/test-page/).

**Comment by BigBoyBarney** [comment]
I'm using Linux, and I tested it on 3 different images, same error on all of them. However, after updating Pillow as well (from 9.5.0 to 10.2.0), it now works 🥳

I have no idea why 9.5.0 didn't recognise the image, maybe there's something in the plugin that's not compatible? In any case, it might be worth noting in the readme that if somebody encounters that error, they should make sure that Pillow is up to date.

Thank you for the fix!

**Comment by BigBoyBarney** [comment]
Actually never mind, opening and loading images works, saving does not.

https://www.swisstransfer.com/d/0ac14f2b-db0a-4ecc-b766-40fb2560b68b
I uploaded one of the images I opened (`1.jxl`) and the output of the save after resizing 2x. (`test_2x.jxl`)

The code was
```python
from PIL import Image
from jxlpy import JXLImagePlugin

im = Image.open('1.jxl')
im = im.resize((im.width*2, im.height*2))
im.save('test_2x.jxl', lossless=True, effort=7)
```

**Comment by C0rn3j** [comment]
#26 fixed this even with older Pillow, the issue can be closed.
